import {
  Activity,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowUp,
  Ban,
  Briefcase,
  Cable,
  Calendar,
  Camera,
  ChartArea,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleAlert,
  CircleArrowUp,
  CircleCheck,
  CircleX,
  Clock,
  Copy,
  Cpu,
  Download,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Gauge,
  Globe,
  HardDrive,
  House,
  Image,
  Info,
  KeyRound,
  Layers,
  LayoutDashboard,
  Link,
  List,
  ListChecks,
  Lock,
  LogOut,
  Mail,
  Monitor,
  Moon,
  Network,
  Pencil,
  Play,
  PlugZap,
  Plus,
  Power,
  QrCode,
  RefreshCw,
  Rocket,
  Route,
  Router,
  Save,
  ScrollText,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sun,
  Terminal,
  Trash2,
  TriangleAlert,
  Unplug,
  User,
  UserPlus,
  Users,
  Waypoints,
  X,
  Zap,
} from "lucide-react-native";
import { ComponentType } from "react";

import { IIconGlyphProps } from "./icon.types";
import { CheckBoldIcon, CloseCircleFilledIcon } from "./icons";

/**
 * Реестр иконок приложения.
 *
 * Добавить lucide-иконку: импорт из `lucide-react-native` → строка в map.
 * Добавить кастомную: компонент по контракту `IIconGlyphProps`
 * (пример — `icons/CheckBold.tsx`) → строка в map. Имя подхватится
 * типом `TIconName` и галереей (`ICON_NAMES`) автоматически.
 */
export const ICONS_MAP = {
  activity: Activity,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  back: ArrowLeft,
  ban: Ban,
  briefcase: Briefcase,
  cable: Cable,
  calendar: Calendar,
  camera: Camera,
  chart: ChartArea,
  check: Check,
  checkBold: CheckBoldIcon,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  circleAlert: CircleAlert,
  circleCheck: CircleCheck,
  clock: Clock,
  close: X,
  closeCircle: CircleX,
  closeCircleFilled: CloseCircleFilledIcon,
  copy: Copy,
  cpu: Cpu,
  dashboard: LayoutDashboard,
  document: FileText,
  download: Download,
  edit: Pencil,
  externalLink: ExternalLink,
  eye: Eye,
  eyeOff: EyeOff,
  gauge: Gauge,
  globe: Globe,
  hardDrive: HardDrive,
  home: House,
  image: Image,
  info: Info,
  key: KeyRound,
  layers: Layers,
  link: Link,
  list: List,
  listChecks: ListChecks,
  lock: Lock,
  logOut: LogOut,
  mail: Mail,
  monitor: Monitor,
  moon: Moon,
  more: Ellipsis,
  moreVertical: EllipsisVertical,
  network: Network,
  play: Play,
  plugZap: PlugZap,
  plus: Plus,
  power: Power,
  qrCode: QrCode,
  refresh: RefreshCw,
  rocket: Rocket,
  route: Route,
  router: Router,
  save: Save,
  scrollText: ScrollText,
  search: Search,
  server: Server,
  settings: Settings,
  share: Share2,
  shield: Shield,
  shieldCheck: ShieldCheck,
  sliders: SlidersHorizontal,
  smartphone: Smartphone,
  sun: Sun,
  swap: ArrowLeftRight,
  terminal: Terminal,
  trash: Trash2,
  unplug: Unplug,
  upgrade: CircleArrowUp,
  user: User,
  userPlus: UserPlus,
  users: Users,
  warning: TriangleAlert,
  waypoints: Waypoints,
  zap: Zap,
} satisfies Record<string, ComponentType<IIconGlyphProps>>;

export type TIconName = keyof typeof ICONS_MAP;

/** Все имена иконок набора (галереи, демо, итерация). */
export const ICON_NAMES = Object.keys(ICONS_MAP) as TIconName[];
