/**
 * Русские подписи классов модели детекции объектов — по имени класса
 * из метаданных модели. Класс без подписи показывается своим именем.
 */
export const OBJECT_CLASS_TITLES: Record<string, string> = {
  person: "Человек",
  bicycle: "Велосипед",
  car: "Автомобиль",
  motorcycle: "Мотоцикл",
  airplane: "Самолёт",
  bus: "Автобус",
  train: "Поезд",
  truck: "Грузовик",
  boat: "Лодка",
  "traffic light": "Светофор",
  "fire hydrant": "Пожарный гидрант",
  "stop sign": "Знак остановки",
  "parking meter": "Паркомат",
  bench: "Скамейка",
  bird: "Птица",
  cat: "Кошка",
  dog: "Собака",
  horse: "Лошадь",
  sheep: "Овца",
  cow: "Корова",
  elephant: "Слон",
  bear: "Медведь",
  zebra: "Зебра",
  giraffe: "Жираф",
  backpack: "Рюкзак",
  umbrella: "Зонт",
  handbag: "Сумка",
  tie: "Галстук",
  suitcase: "Чемодан",
  frisbee: "Летающая тарелка",
  skis: "Лыжи",
  snowboard: "Сноуборд",
  "sports ball": "Мяч",
  kite: "Воздушный змей",
  "baseball bat": "Бейсбольная бита",
  "baseball glove": "Бейсбольная перчатка",
  skateboard: "Скейтборд",
  surfboard: "Сёрфборд",
  "tennis racket": "Теннисная ракетка",
  bottle: "Бутылка",
  "wine glass": "Бокал",
  cup: "Чашка",
  fork: "Вилка",
  knife: "Нож",
  spoon: "Ложка",
  bowl: "Миска",
  banana: "Банан",
  apple: "Яблоко",
  sandwich: "Сэндвич",
  orange: "Апельсин",
  broccoli: "Брокколи",
  carrot: "Морковь",
  "hot dog": "Хот-дог",
  pizza: "Пицца",
  donut: "Пончик",
  cake: "Торт",
  chair: "Стул",
  couch: "Диван",
  "potted plant": "Комнатное растение",
  bed: "Кровать",
  "dining table": "Обеденный стол",
  toilet: "Унитаз",
  tv: "Телевизор",
  laptop: "Ноутбук",
  mouse: "Мышь",
  remote: "Пульт",
  keyboard: "Клавиатура",
  "cell phone": "Мобильный телефон",
  microwave: "Микроволновая печь",
  oven: "Духовка",
  toaster: "Тостер",
  sink: "Раковина",
  refrigerator: "Холодильник",
  book: "Книга",
  clock: "Часы",
  vase: "Ваза",
  scissors: "Ножницы",
  "teddy bear": "Плюшевый мишка",
  "hair drier": "Фен",
  toothbrush: "Зубная щётка",
};
