package com.rnapp.rnchatview

import android.graphics.Color

data class ChatTheme(
    val outgoingBubbleColor: Int,
    val outgoingTextColor: Int,
    val outgoingTimeColor: Int,
    val outgoingStatusColor: Int,
    val outgoingStatusReadColor: Int,
    val outgoingEditedColor: Int,
    val incomingBubbleColor: Int,
    val incomingTextColor: Int,
    val incomingTimeColor: Int,
    val incomingEditedColor: Int,
    val outgoingReplyBackground: Int,
    val outgoingReplyAccent: Int,
    val outgoingReplySender: Int,
    val outgoingReplyText: Int,
    val incomingReplyBackground: Int,
    val incomingReplyAccent: Int,
    val incomingReplySender: Int,
    val incomingReplyText: Int,
    val inputBarBackground: Int,
    val inputBarSeparator: Int,
    val inputBarTextViewBg: Int,
    val inputBarPlaceholder: Int,
    val inputBarText: Int,
    val inputBarTint: Int,
    val replyPanelBackground: Int,
    val replyPanelAccent: Int,
    val replyPanelSender: Int,
    val replyPanelText: Int,
    val replyPanelClose: Int,
    val dateSeparatorBackground: Int,
    val dateSeparatorText: Int,
    val fabBackground: Int,
    val fabArrowColor: Int,
    val emptyStateText: Int,
    val collectionBackground: Int,
    val isDark: Boolean,
) {
    companion object {

        /** Создаёт светлую тему. */
        fun light() = ChatTheme(
            outgoingBubbleColor = Color.rgb(61, 158, 249),
            outgoingTextColor = Color.WHITE,
            outgoingTimeColor = Color.argb(191, 255, 255, 255),
            outgoingStatusColor = Color.argb(178, 255, 255, 255),
            outgoingStatusReadColor = Color.WHITE,
            outgoingEditedColor = Color.argb(153, 255, 255, 255),
            incomingBubbleColor = Color.rgb(240, 240, 240),
            incomingTextColor = Color.BLACK,
            incomingTimeColor = Color.rgb(142, 142, 147),
            incomingEditedColor = Color.rgb(142, 142, 147),
            outgoingReplyBackground = Color.argb(51, 255, 255, 255),
            outgoingReplyAccent = Color.argb(178, 255, 255, 255),
            outgoingReplySender = Color.argb(229, 255, 255, 255),
            outgoingReplyText = Color.argb(217, 255, 255, 255),
            incomingReplyBackground = Color.argb(15, 0, 0, 0),
            incomingReplyAccent = Color.rgb(0, 122, 255),
            incomingReplySender = Color.rgb(0, 122, 255),
            incomingReplyText = Color.rgb(142, 142, 147),
            inputBarBackground = Color.WHITE,
            inputBarSeparator = Color.argb(77, 60, 60, 67),
            inputBarTextViewBg = Color.rgb(242, 242, 247),
            inputBarPlaceholder = Color.rgb(199, 199, 204),
            inputBarText = Color.BLACK,
            inputBarTint = Color.rgb(0, 122, 255),
            replyPanelBackground = Color.WHITE,
            replyPanelAccent = Color.rgb(0, 122, 255),
            replyPanelSender = Color.rgb(0, 122, 255),
            replyPanelText = Color.rgb(142, 142, 147),
            replyPanelClose = Color.rgb(199, 199, 204),
            dateSeparatorBackground = Color.argb(217, 242, 242, 247),
            dateSeparatorText = Color.rgb(142, 142, 147),
            fabBackground = Color.WHITE,
            fabArrowColor = Color.BLACK,
            emptyStateText = Color.rgb(142, 142, 147),
            collectionBackground = Color.TRANSPARENT,
            isDark = false,
        )

        /** Создаёт тёмную тему. */
        fun dark() = ChatTheme(
            outgoingBubbleColor = Color.rgb(36, 115, 204),
            outgoingTextColor = Color.WHITE,
            outgoingTimeColor = Color.argb(166, 255, 255, 255),
            outgoingStatusColor = Color.argb(153, 255, 255, 255),
            outgoingStatusReadColor = Color.argb(229, 255, 255, 255),
            outgoingEditedColor = Color.argb(128, 255, 255, 255),
            incomingBubbleColor = Color.rgb(46, 46, 46),
            incomingTextColor = Color.rgb(237, 237, 237),
            incomingTimeColor = Color.rgb(140, 140, 140),
            incomingEditedColor = Color.rgb(140, 140, 140),
            outgoingReplyBackground = Color.argb(38, 255, 255, 255),
            outgoingReplyAccent = Color.argb(153, 255, 255, 255),
            outgoingReplySender = Color.argb(217, 255, 255, 255),
            outgoingReplyText = Color.argb(191, 255, 255, 255),
            incomingReplyBackground = Color.argb(20, 255, 255, 255),
            incomingReplyAccent = Color.rgb(89, 153, 255),
            incomingReplySender = Color.rgb(89, 153, 255),
            incomingReplyText = Color.rgb(153, 153, 153),
            inputBarBackground = Color.rgb(31, 31, 31),
            inputBarSeparator = Color.argb(26, 255, 255, 255),
            inputBarTextViewBg = Color.rgb(56, 56, 56),
            inputBarPlaceholder = Color.rgb(115, 115, 115),
            inputBarText = Color.rgb(237, 237, 237),
            inputBarTint = Color.rgb(89, 153, 255),
            replyPanelBackground = Color.rgb(31, 31, 31),
            replyPanelAccent = Color.rgb(89, 153, 255),
            replyPanelSender = Color.rgb(89, 153, 255),
            replyPanelText = Color.rgb(153, 153, 153),
            replyPanelClose = Color.rgb(102, 102, 102),
            dateSeparatorBackground = Color.argb(230, 51, 51, 51),
            dateSeparatorText = Color.rgb(153, 153, 153),
            fabBackground = Color.rgb(44, 44, 46),
            fabArrowColor = Color.rgb(229, 229, 229),
            emptyStateText = Color.rgb(128, 128, 128),
            collectionBackground = Color.TRANSPARENT,
            isDark = true,
        )

        /** Создаёт тему по имени. */
        fun from(name: String?) = if (name?.lowercase() == "dark") dark() else light()
    }
}
