/** Демо-экраны кита: маршрут корневого стека и подпись ссылки. */
export const COMPONENT_DEMOS = [
  { route: "ComponentsButtons", title: "Buttons" },
  { route: "ComponentsTypography", title: "Typography" },
  { route: "ComponentsIcons", title: "Icons" },
  { route: "ComponentsInputs", title: "Inputs" },
  { route: "ComponentsKeyboardScroll", title: "Keyboard · Scroll" },
  { route: "ComponentsKeyboardSheet", title: "Keyboard · Sheet" },
  { route: "ComponentsKeyboardAnchorList", title: "Keyboard · AnchorList" },
  { route: "ComponentsControls", title: "Controls" },
  { route: "ComponentsForms", title: "Forms" },
  { route: "ComponentsLayout", title: "Layout" },
  { route: "ComponentsLists", title: "Lists" },
  { route: "ComponentsData", title: "Data" },
  { route: "ComponentsSettings", title: "Settings" },
  { route: "ComponentsScreen", title: "Screen" },
  { route: "ComponentsScreenReady", title: "ScreenReady" },
  { route: "ComponentsScrollReveal", title: "Scroll reveal" },
  { route: "ComponentsSearch", title: "Search · Navbar" },
  { route: "ComponentsSearchHiddenBar", title: "Search · Hidden bar" },
  { route: "ComponentsTabs", title: "Tabs" },
  { route: "ComponentsFeedback", title: "Feedback" },
  { route: "ComponentsMedia", title: "Media" },
  { route: "ComponentsCarousel", title: "Carousel" },
  { route: "ComponentsNotifications", title: "Notifications" },
  { route: "ComponentsModals", title: "Modals" },
  { route: "ComponentsDialogs", title: "Dialogs" },
  { route: "ComponentsPickers", title: "Pickers" },
  { route: "ComponentsTicket", title: "Ticket" },
  { route: "ComponentsCharts", title: "Charts" },
  { route: "ComponentsCalendar", title: "Calendar" },
  { route: "ComponentsCalendarList", title: "Calendar list" },
  { route: "ComponentsContextMenu", title: "Context menu" },
  { route: "ComponentsInputBar", title: "Input bar" },
] as const;
